prog: main.o background.o back.o button.o es.o pers.o map.o time.o collisionparfaite.o fonction.o
	gcc main.o background.o back.o button.o es.o pers.o map.o time.o collisionparfaite.o fonction.o -o prog -lSDL -g -lSDL_image -lSDL_mixer -lm -lSDL_ttf
main.o: main.c
	gcc -c main.c -g
background.o: background.c
	gcc -c background.c -g
back.o: back.c
	gcc -c back.c -g
button.o: button.c
	gcc -c button.c -g

es.o: es.c
	gcc -c es.c -g


pers.o: pers.c
	gcc -c pers.c -g


map.o: map.c
	gcc -c map.c -g

time.o: time.c
	gcc -c time.c -g

collisionparfaite.o: collisionparfaite.c
	gcc -c collisionparfaite.c -g

fonction.o: fonction.c
	gcc -c fonction.c -g




